"""SQLite-backed persistent task queue with atomic dequeue.

WAL mode for concurrent reads from web + daemon processes.
"""

import json
import os
import sqlite3
import time
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)

# Default DB path relative to project root
DEFAULT_DB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "tasks.db")


class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class TaskType(str, Enum):
    MANUAL = "manual"          # User-submitted via UI/CLI
    HEARTBEAT = "heartbeat"    # Auto-generated by heartbeat checks
    SCHEDULED = "scheduled"    # Cron-triggered
    WEBHOOK = "webhook"        # External trigger


@dataclass
class Task:
    """In-memory representation of a queued task."""
    id: int
    status: str
    priority: int
    task_type: str
    payload: dict
    result: dict | None
    created_at: float
    started_at: float | None
    completed_at: float | None
    attempts: int
    max_attempts: int
    error: str | None
    parent_id: int | None
    metadata: dict


class TaskQueue:
    """SQLite-backed task queue with WAL mode for concurrent access."""

    def __init__(self, db_path: str | None = None):
        self.db_path = db_path or DEFAULT_DB_PATH
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self._init_db()

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path, timeout=10)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA busy_timeout=5000")
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self):
        with self._connect() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS tasks (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    status TEXT NOT NULL DEFAULT 'pending',
                    priority INTEGER NOT NULL DEFAULT 0,
                    task_type TEXT NOT NULL DEFAULT 'manual',
                    payload TEXT NOT NULL DEFAULT '{}',
                    result TEXT,
                    created_at REAL NOT NULL,
                    started_at REAL,
                    completed_at REAL,
                    attempts INTEGER NOT NULL DEFAULT 0,
                    max_attempts INTEGER NOT NULL DEFAULT 3,
                    error TEXT,
                    parent_id INTEGER,
                    metadata TEXT NOT NULL DEFAULT '{}',
                    FOREIGN KEY (parent_id) REFERENCES tasks(id)
                )
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_tasks_status_priority
                ON tasks (status, priority DESC, created_at ASC)
            """)

    def _row_to_task(self, row: sqlite3.Row) -> Task:
        return Task(
            id=row["id"],
            status=row["status"],
            priority=row["priority"],
            task_type=row["task_type"],
            payload=json.loads(row["payload"]),
            result=json.loads(row["result"]) if row["result"] else None,
            created_at=row["created_at"],
            started_at=row["started_at"],
            completed_at=row["completed_at"],
            attempts=row["attempts"],
            max_attempts=row["max_attempts"],
            error=row["error"],
            parent_id=row["parent_id"],
            metadata=json.loads(row["metadata"]),
        )

    # ---- Core operations ----

    def enqueue(
        self,
        task_text: str,
        project_path: str,
        priority: int = 0,
        task_type: str = TaskType.MANUAL,
        max_attempts: int = 3,
        parent_id: int | None = None,
        metadata: dict | None = None,
    ) -> int:
        """Add a task to the queue. Returns the task ID."""
        payload = json.dumps({"task": task_text, "project": project_path})
        meta = json.dumps(metadata or {})
        now = time.time()

        with self._connect() as conn:
            cursor = conn.execute(
                """INSERT INTO tasks (status, priority, task_type, payload,
                   created_at, max_attempts, parent_id, metadata)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (TaskStatus.PENDING, priority, task_type, payload,
                 now, max_attempts, parent_id, meta),
            )
            task_id = cursor.lastrowid

        logger.info("Enqueued task #%d: %s (priority=%d)", task_id, task_text[:80], priority)
        return task_id

    def dequeue(self) -> Task | None:
        """Atomically claim the highest-priority pending task.

        Returns the task (now status=running) or None if queue is empty.
        Uses a single UPDATE+SELECT to avoid race conditions between
        multiple daemon processes.
        """
        with self._connect() as conn:
            now = time.time()
            # Atomic: pick the top pending task and mark it running
            conn.execute(
                """UPDATE tasks SET status = ?, started_at = ?, attempts = attempts + 1
                   WHERE id = (
                       SELECT id FROM tasks
                       WHERE status = ?
                       ORDER BY priority DESC, created_at ASC
                       LIMIT 1
                   )""",
                (TaskStatus.RUNNING, now, TaskStatus.PENDING),
            )
            # Fetch the task we just claimed
            row = conn.execute(
                "SELECT * FROM tasks WHERE status = ? AND started_at = ?",
                (TaskStatus.RUNNING, now),
            ).fetchone()

        if row:
            task = self._row_to_task(row)
            logger.info("Dequeued task #%d: %s", task.id, task.payload.get("task", "")[:80])
            return task
        return None

    def complete(self, task_id: int, result: dict | None = None):
        """Mark a task as completed."""
        with self._connect() as conn:
            conn.execute(
                """UPDATE tasks SET status = ?, completed_at = ?, result = ?
                   WHERE id = ?""",
                (TaskStatus.COMPLETED, time.time(),
                 json.dumps(result) if result else None, task_id),
            )
        logger.info("Task #%d completed", task_id)

    def fail(self, task_id: int, error: str):
        """Mark a task as failed. Auto-retries if under max_attempts."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT attempts, max_attempts FROM tasks WHERE id = ?",
                (task_id,),
            ).fetchone()

            if row and row["attempts"] < row["max_attempts"]:
                # Requeue for retry
                conn.execute(
                    "UPDATE tasks SET status = ?, error = ? WHERE id = ?",
                    (TaskStatus.PENDING, error, task_id),
                )
                logger.info("Task #%d failed (attempt %d/%d), requeued: %s",
                            task_id, row["attempts"], row["max_attempts"], error[:100])
            else:
                # Max attempts reached
                conn.execute(
                    """UPDATE tasks SET status = ?, completed_at = ?, error = ?
                       WHERE id = ?""",
                    (TaskStatus.FAILED, time.time(), error, task_id),
                )
                logger.warning("Task #%d failed permanently: %s", task_id, error[:100])

    def cancel(self, task_id: int) -> bool:
        """Cancel a pending task. Returns False if task is already running/done."""
        with self._connect() as conn:
            cursor = conn.execute(
                "UPDATE tasks SET status = ? WHERE id = ? AND status = ?",
                (TaskStatus.CANCELLED, task_id, TaskStatus.PENDING),
            )
            return cursor.rowcount > 0

    def retry(self, task_id: int) -> bool:
        """Manually retry a failed/cancelled task."""
        with self._connect() as conn:
            cursor = conn.execute(
                """UPDATE tasks SET status = ?, error = NULL, started_at = NULL,
                   completed_at = NULL WHERE id = ? AND status IN (?, ?)""",
                (TaskStatus.PENDING, task_id, TaskStatus.FAILED, TaskStatus.CANCELLED),
            )
            return cursor.rowcount > 0

    def cleanup_stale(self, timeout_seconds: int = 600) -> int:
        """Reset tasks stuck in 'running' for too long (e.g. daemon crash).

        Returns number of tasks reset.
        """
        cutoff = time.time() - timeout_seconds
        with self._connect() as conn:
            cursor = conn.execute(
                """UPDATE tasks SET status = ?, error = 'Stale: daemon timeout'
                   WHERE status = ? AND started_at < ?""",
                (TaskStatus.PENDING, TaskStatus.RUNNING, cutoff),
            )
            count = cursor.rowcount
        if count:
            logger.warning("Reset %d stale tasks", count)
        return count

    # ---- Query operations ----

    def get(self, task_id: int) -> Task | None:
        """Get a single task by ID."""
        with self._connect() as conn:
            row = conn.execute("SELECT * FROM tasks WHERE id = ?", (task_id,)).fetchone()
        return self._row_to_task(row) if row else None

    def list_tasks(
        self,
        status: str | None = None,
        task_type: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Task]:
        """List tasks with optional filters."""
        query = "SELECT * FROM tasks WHERE 1=1"
        params: list[Any] = []

        if status:
            query += " AND status = ?"
            params.append(status)
        if task_type:
            query += " AND task_type = ?"
            params.append(task_type)

        query += " ORDER BY created_at DESC LIMIT ? OFFSET ?"
        params.extend([limit, offset])

        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [self._row_to_task(r) for r in rows]

    def count(self, status: str | None = None) -> int:
        """Count tasks, optionally filtered by status."""
        if status:
            with self._connect() as conn:
                row = conn.execute(
                    "SELECT COUNT(*) as c FROM tasks WHERE status = ?", (status,)
                ).fetchone()
        else:
            with self._connect() as conn:
                row = conn.execute("SELECT COUNT(*) as c FROM tasks").fetchone()
        return row["c"] if row else 0

    def pending_count(self) -> int:
        return self.count(TaskStatus.PENDING)

    def stats(self) -> dict:
        """Get queue statistics."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT status, COUNT(*) as c FROM tasks GROUP BY status"
            ).fetchall()
        counts = {row["status"]: row["c"] for row in rows}
        return {
            "pending": counts.get("pending", 0),
            "running": counts.get("running", 0),
            "completed": counts.get("completed", 0),
            "failed": counts.get("failed", 0),
            "cancelled": counts.get("cancelled", 0),
            "total": sum(counts.values()),
        }
